# Generated by Django 5.2.3 on 2025-06-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.JSONField(help_text='A list or dictionary of foods consumed. Expected to be a structured JSON object.')),
                ('is_veg', models.BooleanField(help_text='Indicates whether the foods suggest a vegetarian or vegan diet. True if vegetarian/vegan, False otherwise.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this simulated conversation was created.')),
            ],
        ),
    ]
